---
- hosts: nginx
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install NGINX
      apt:
        name: nginx
        state: present

    - name: Start and enable NGINX service
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Deploy custom index.html
      copy:
        src: /path/to/html/index.html
        dest: /var/www/html/index.html
        remote_src: yes
        mode: '0644'
