---
- hosts: nginx
  tasks:
    - name: Stop NGINX service
      service:
        name: nginx
        state: stopped
        enabled: no

    - name: Uninstall NGINX
      apt:
        name: nginx
        state: absent

    - name: Remove NGINX configuration and content
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/nginx
        - /var/www/html
        - /var/log/nginx
